### ISSUE TITLE
Improve the Github community profile score for The Good Docs org (EPIC)

### ISSUE THREAD

**Issue by barbaricyawps** [thegooddocs/governance#12]
### The proposal

Improve the [Github community profile](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-community-profiles-for-public-repositories) score for The Good Docs by:

1. Either adding a .github repo or converting the governance repo to a .github repo. See [Creating a default community health profile](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file)
2. Ensuring this repo has the necessary documents and processes that Github requires.

### Our current status

Our score right now is uneven across repos and has room for improvement. For comparison see the community health score for the [templates repo](https://github.com/thegooddocsproject/templates/community) vs. the [governance repo](https://github.com/thegooddocsproject/governance/community). The necessary docs are:

- [x] Description
- [x] README
- [ ] [Code of Conduct](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project) NOTE: This exists, but needs to be improved
- [ ] [Contributing](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors) NOTE: This exists, but not in every repo across the org
- [x] [License](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository)
- [ ] [Issue templates](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates)
- [ ] [Pull request template](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates) NOTE: This exists, but not in every repo across the org
- [ ] [Repository admins accept content reports](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/managing-how-contributors-report-abuse-in-your-organizations-repository)

### Why should we do this?

First, many new project contributors use this community health meter when deciding whether to contribute to a project. Second, if our mission statement is to help improve documentation in open source, then we need to model this behavior ourselves. That starts by having the docs that Github considers a sign of community health. And, of course, let’s ensure that they are high quality docs!
